baseURL = 'https://www.yichenphoto.com/'
languageCode = 'en-us'
title = 'Yi Chen Photography'
theme = "augohugo"

#googleAnalytics = ""

[Author]
    name = "Yi Chen"
    email = "yichen@gmail.com"

[params]
    # Meta
    description = "Yi Chen's photo gallery"
    keywords = "yi chen, photo, photography"
    #thumb_width = 480
    thumb_width = 300
    thumb_quality = 80
    #full_width = 960
    full_width = 600
    full_quality = 100
    column_count = 4
    #breadcrumb_use_title = false
    #filename_as_phototitle = false
    #images_downloadable = true
    #images_downloadable_use_orig = false
    #taxonomies_links = false

    # Headerbar links
    # Do not put too many links here,
    # it will break mobile appearance
